name: carpenter-pro-backend
region: nyc
services:
- name: api
  github:
    branch: main
    deploy_on_push: true
    repo: bradz86/carpenter-pro-backend
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xs
  routes:
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: NODE_ENV
    scope: RUN_TIME
    value: production
  - key: BRIGHT_DATA_USERNAME
    scope: RUN_TIME
    type: SECRET
  - key: BRIGHT_DATA_PASSWORD
    scope: RUN_TIME
    type: SECRET
  - key: ADMIN_KEY
    scope: RUN_TIME
    type: SECRET
  - key: JWT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: PORT
    scope: RUN_TIME
    value: "3000"
databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "14"
